version: "2"

run:
  tests: true

linters:
  default: standard
  enable:
    - dupl
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
  settings:
    dupl:
      threshold: 100
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G404 # Insecure random number source (rand).
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
  rules:
    - linters:
        - revive
      severity: warning
