version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./:/root
    depends_on:
      - redis
    networks:
      - app-network
    command: [
      "./bot",
      "-history=${HISTORY:-}", # for example: /root/result.json
      "-prompt=${PROMPT:-/root/prompt.txt}",
      "-model=${MODEL:-claude-3-7-sonnet-latest}",
      "-provider=${PROVIDER:-anthropic}",
      "-spam-threshold=${SPAM_THRESHOLD}", #0.5
      "-new-user-threshold=${NEW_USER_THRESHOLD:-1}",
      "-whitelist-channels=${WHITELIST_CHANNELS}", # comma separated, for example: "-1001098030726" (CTO daily chat)
      "-log-level=${LOG_LEVEL:-info}",
      "-log-channels=${LOG_CHANNELS}" # comma-separated list of working chat ID and log channel ID pairs, for example: "-1001098030726:-1001089898989,-1001098030727:-1001089898990" (first pair: CTO daily chat and its log channel, second pair: another chat and its log channel)
    ]

  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel warning --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge